### ISSUE TITLE
weird str() in code

### ISSUE THREAD

**Issue by Akuli** [adder46/pyhstr#11]
https://github.com/adder46/pyhstr/blob/ae09033cce44f109a42ca325e1cba50130ad653a/pyhstr/application.py#L91

To me, this seems like this code may create a file named `None` by calling `readline.write_history_file(str(None))`, but I'm not sure.

**Comment by adder46** [comment]
Well, it's never going to be None since that happens for standard shell, and the dict has the hist value for it. I added str() to satisfy mypy, but suggestions are welcome.

**Comment by adder46** [comment]
Whoops, I just saw your pull request.
